# This is a basic workflow to help you get started with Actions

name: wsgi_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: wsgi-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            wsgi-
      # Install python 3.
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # install apache 2 apache2
      - name: Install apache 2
        run: |
          sudo apt install apache2
      - name: Install wsgi
        run: |
         sudo apt-get install libapache2-mod-wsgi-py3
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      # NEXT
      # https://techtutorguro.com/how-to-install-flask-on-ubuntu-22-04-with-apache/
      - name: mv wsgi to folder
        run: |
          ls -l /var/www/
          sudo mkdir -p /var/www/DrillMaster/
          ls -l /var/www/
          ls -l /var/www/DrillMaster/
          sudo mv drillmaster.wsgi /var/www/DrillMaster/
      # move apache virtual host to folder
      - name: mv virtual site to folder
        run: |
          mv ./rsc/dev.drillmaster.conf /etc/apache2/sites-available/drillmaster.conf
          a2ensite drillmaster.conf
          systemctl restart apache2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: wget localhost

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
